from .veo3 import NODE_CLASS_MAPPINGS as VEO3_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as VEO3_DISPLAY_MAPPINGS
from .batch_processor import NODE_CLASS_MAPPINGS as BATCH_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as BATCH_DISPLAY_MAPPINGS

NODE_CLASS_MAPPINGS = {**VEO3_MAPPINGS, **BATCH_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**VEO3_DISPLAY_MAPPINGS, **BATCH_DISPLAY_MAPPINGS}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']