"""配套能力节点模块"""

from .image_upload import (
    UploadToImageHost,
    NODE_CLASS_MAPPINGS as UPLOAD_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as UPLOAD_DISPLAY_MAPPINGS
)

from .audio_upload import (
    UploadAudioToHost,
    NODE_CLASS_MAPPINGS as AUDIO_UPLOAD_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as AUDIO_UPLOAD_DISPLAY_MAPPINGS
)

from .deepseek_ocr import (
    DeepseekOCRToPrompt,
    NODE_CLASS_MAPPINGS as OCR_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as OCR_DISPLAY_MAPPINGS
)

from .video_download import (
    DownloadVideo,
    PreviewVideo,
    NODE_CLASS_MAPPINGS as VIDEO_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as VIDEO_DISPLAY_MAPPINGS
)

from .csv_reader import (
    CSVBatchReader,
    NODE_CLASS_MAPPINGS as CSV_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as CSV_DISPLAY_MAPPINGS
)

# 合并所有节点映射
NODE_CLASS_MAPPINGS = {}
NODE_CLASS_MAPPINGS.update(UPLOAD_MAPPINGS)
NODE_CLASS_MAPPINGS.update(AUDIO_UPLOAD_MAPPINGS)
NODE_CLASS_MAPPINGS.update(OCR_MAPPINGS)
NODE_CLASS_MAPPINGS.update(VIDEO_MAPPINGS)
NODE_CLASS_MAPPINGS.update(CSV_MAPPINGS)

NODE_DISPLAY_NAME_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS.update(UPLOAD_DISPLAY_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(AUDIO_UPLOAD_DISPLAY_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(OCR_DISPLAY_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(VIDEO_DISPLAY_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(CSV_DISPLAY_MAPPINGS)

__all__ = [
    "NODE_CLASS_MAPPINGS",
    "NODE_DISPLAY_NAME_MAPPINGS",
    "UploadToImageHost",
    "UploadAudioToHost",
    "DeepseekOCRToPrompt",
    "DownloadVideo",
    "PreviewVideo",
    "CSVBatchReader",
]
